name: Build Firmware
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # This workflow is triggered every day at 00:00 UTC
    - cron: '0 0 * * *'

# Matrix with different config files.
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [btteddy_usb, ender3s1pro_f401]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create output directory
        run: mkdir -p out

      - name: Build firmware with docker
        run: docker build --build-arg BUILD_CONFIG_FILE=${{ matrix.config }}.conf --output=out .

      - name: Remove unnecessary files
        run: |
          # Remove any .o files
          find out -type f -name "*.o" -delete

          # Remove any .d files
          find out -type f -name "*.d" -delete

          # Remove any .a files
          find out -type f -name "*.a" -delete

          # Remove any .map files
          find out -type f -name "*.map" -delete

          # Remove any stage2 files
          find out -type f -name "stage2*" -delete

      - name: Rename output files
        run: |
          # Rename anything with .bin extension if files exist
          if ls out/*.bin 1> /dev/null 2>&1; then
            for file in out/*.bin; do
              mv -v "$file" "${file%.bin}_${{ matrix.config }}.bin"
            done
          fi

          # Rename anything with .elf extension if files exist
          if ls out/*.elf 1> /dev/null 2>&1; then
            for file in out/*.elf; do
              mv -v "$file" "${file%.elf}_${{ matrix.config }}.elf"
            done
          fi

          # Rename anything with .uf2 extension if files exist
          if ls out/*.uf2 1> /dev/null 2>&1; then
            for file in out/*.uf2; do
              mv -v "$file" "${file%.uf2}_${{ matrix.config }}.uf2"
            done
          fi

      - name: Upload bin firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.config }}.bin
          path: out/*.bin
          compression-level: 0
      
      - name: Upload elf firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.config }}.elf
          path: out/*.elf
          compression-level: 0

      - name: Upload uf2 firmware
        uses: actions/upload-artifact@v4
        if: ${{ matrix.config }} == "btteddy_usb"
        with:
          name: firmware-${{ matrix.config }}.uf2
          path: out/*.uf2
          compression-level: 0

        
    
